spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  datasource:
    username: test
    password: test
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/test?useSSL=false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
